packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false

minimumReleaseAgeExclude:
  - '@linxin666/*'
  - '@nanmicoder/dsh-agent-teams@0.1.5'
  - dsh-better-sidebar@0.12.2
  - dshmarket@1.8.0
  - dsh-harness-zh-cn@0.1.2

allowBuilds:
  node-pty: true
